server:
  port: 8080

spring:
  datasource:
    username: skillbox #root
    password: skillbox #1234
    url: jdbc:postgresql://localhost:5432/search_engine
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:changelog.xml
  logging:
    level:
      liquibase: DEBUG

http:
  user-agent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) HeliontSearchBot/20070725 Firefox/2.0.0.6
  referrer: http://www.google.com
  timeout: 1000 #//1 секунда

indexing-settings:
  sites:
    - url: https://sendel.ru/
      name: sendel
    - url: https://nikoartgallery.com/
      name: nikoartgallery
      #- url: https://www.lenta.ru
      #name: Лента.ру
      #- url: https://www.skillbox.ru
      #name: Skillbox
      #- url: https://www.playback.ru
      #name: PlayBack.Ru
